version: '2.0'
services:
  accel-pppd:
    image: dr4g0nsr/accel-pppd:latest
    hostname: accel-pppd
    container_name: accel-pppd
    network_mode: host
#    ports:
#      - 2000:2000/tcp
#      - 2001:2001/tcp
    volumes:
      - "./log:/var/log/accel-ppp"
#      - "./accel-ppp.conf:/etc/accel-ppp.conf"
    environment:
      INTERFACE: 'ens192'
      RADIUS: 'radius'
      RADIUS_PASSWORD: 'testing123'
#      PPPOE_SERVICE_NAME: 'docker'
      PPPOE_AC_NAME: 'docker'
      PPPOE: 1
      IPOE: 0
      PPTP: 0
      L2TP: 0
      SSTP: 0
    stdin_open: true
    tty: true