version: '2.0'
services:
  accel-pppd:
    image: dr4g0nsr/accel-pppd:latest
    hostname: accel-pppd
    container_name: accel-pppd
    network_mode: host
#    ports:
#      - 2000:2000/tcp
#      - 2001:2001/tcp
    volumes:
      - "./log:/var/log/accel-ppp"
    environment:
      INTERFACE: 'eth0'
      RADIUS: 'radius'
      RADIUS_PASSWORD: 'testing123'
      PPPOE: 1
      IPOE: 0
    stdin_open: true
    tty: true